services:
  medilabo-discovery-service:
    build: ./discovery-service
    container_name: medilabo-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4

  medilabo-config-service:
    build: ./config-service
    container_name: medilabo-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://medilabo-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      medilabo-discovery-service:
        condition: service_healthy

  medilabo-patient-service:
    build: ./patient-service
    container_name: medilabo-patient-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://medilabo-discovery-service:8761/eureka
      - eureka.client.service-url.defaultZone=http://medilabo-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://medilabo-config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      medilabo-config-service:
        condition: service_healthy

  medilabo-medical-record-service:
    build: ./medical-record-service
    container_name: medical-record-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://medilabo-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://medilabo-config-service:9999
      - eureka.client.service-url.defaultZone=http://medilabo-discovery-service:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://medical-db:27017/medicalsdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      medilabo-config-service:
        condition: service_healthy

  medilabo-reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://medilabo-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://medilabo-config-service:9999
      - eureka.client.service-url.defaultZone=http://medilabo-discovery-service:8761/eureka
      - SPRING_DATA_MONGODB_URI=mongodb://medical-db:27017/medicalsdb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      medilabo-config-service:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - medilabo-gateway-service
    environment:
      - API_URL=http://medilabo-gateway-service:8888

  medilabo-gateway-service:
    build: ./gateway-service
    container_name: medilabo-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://medilabo-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://medilabo-config-service:9999
      - eureka.client.service-url.defaultZone=http://medilabo-discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      medilabo-config-service:
        condition: service_healthy

  medical-db:
    image: mongo:6
    container_name: medical-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: medicalsdb

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 5s
      timeout: 10s
      retries: 5

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1